export const TODO_ACTIONS_TYPE = {
  ADD_TODO: "ADD_TODO",
  DELETE_TODO: "DELETE_TODO",
  TOGGLE_TODO: "TOGGLE_TODO",
  UPDATE_TODO: "UPDATE_TODO",
  DUPLICATE_TODO: "DUPLICATE_TODO",
} as const;

export const PRIORITY_ORDER = { High: 1, Medium: 2, Low: 3 };
